name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prepare-dependencies:
    name: Prepare local deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: prepare-env
        uses: ./.github/actions/prepare-local-env
      - name: Use cache or install dependencies
        if: steps.prepare-env.outputs.cache-hit != 'true'
        run: npm ci

  build:
    name: Build source code
    needs: prepare-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-local-env
      - name: Build source code
        run: npm run build
